---
whooshing.sys-authentication:
    domain: "auth"
    pgsql:
        "default":
            database: ["woo"]
            port: 5
    service_bundles:
        "default":
            https:
                hostname: "localhost"
                port: 1
                pg_database_ports: [5]
                domain: "api"
            path: "./bundle"
    shared_inline_module:
        port: 0
        pg_database_ports: [5]
