---
whooshing.sys-authentication:
    domain: "auth"
    pgsql:
        "default":
            database: "woo"
            port: 5
    service_bundles:
        "default":
            https:
                port: 1
                pgDatabasePorts: [5]
                domain: "api"
            path: "./bundle"
    shared_inline_module:
        port: 0
        pgDatabasePorts: [5]
